/* AUTO-GENERATED by gen_whatsnew.py -- DO NOT EDIT */

#define WN_VERSION "1.4.0. Proteus"
#define WN_LOGO_WB 10   /* bytes per row (80px) */
#define WN_LOGO_H  88   /* rows */
#define WN_LOGO_PACKED_SIZE 648
#define WN_CHANGES 3

/* Packed changelog: null-terminated entries, walk with pointer */
static const char wn_changes[] =
    "Native Spectrum Next support\0"
    "New Spectranext paging system\0"
    "And much, much more!\0"
;
