/* AUTO-GENERATED by gen_whatsnew.py -- DO NOT EDIT */

#define WN_VERSION "1.3.9. Juno"
#define WN_LOGO_WB 8   /* bytes per row (64px) */
#define WN_LOGO_H  88   /* rows */
#define WN_LOGO_PACKED_SIZE 765
#define WN_CHANGES 12

/* Packed changelog: null-terminated entries, walk with pointer */
static const char wn_changes[] =
    "Native SpectraNext support\0"
    "Guided SpectraNext installer\0"
    "More reliable UART transfers\0"
    "Safe recovery from UDP failures\0"
    "Reliable configuration loading\0"
    "Safer friend and ignore lists\0"
    "File access preserves the interface\0"
    "More robust About/Earth screen\0"
    "Interrupt-safe chat scrolling\0"
    "Clearer registration errors\0"
    "Polished clock and status UI\0"
    "And much, much more!\0"
;
