/* AUTO-GENERATED by gen_whatsnew.py -- DO NOT EDIT */

#define WN_VERSION "1.4.1. Triton"
#define WN_LOGO_WB 10   /* bytes per row (80px) */
#define WN_LOGO_H  88   /* rows */
#define WN_LOGO_PACKED_SIZE 811
#define WN_CHANGES 6

/* Packed changelog: null-terminated entries, walk with pointer */
static const char wn_changes[] =
    "Automatic IRC service login\0"
    "Spectranext: launch from the web\0"
    "New colour globe on Next\0"
    "Better clock on Next and Spectranext\0"
    "Safer saving of settings\0"
    "And much, much more!\0"
;
