#!/usr/bin/env python3
"""
Generate overlay_defs.asm from the resident binary's .map file.
Provides PUBLIC+DEFC symbols so the overlay C code (compiled separately)
can link against resident functions and variables.

Usage: python gen_overlay_defs.py SpecTalkZX.map > build/overlay_defs.asm
"""

import re
import sys

# --- Minimal ABI surface for overlay C code ---

REQUIRED_FUNCTIONS = [
    # ABI wrappers
    '_overlay_header',

    # Rendering
    '_print_str64',
    '_print_char64',
    '_print_big_str',
    '_clear_line',
    '_draw_badge_dither',
    '_notif_draw',
    '_notif_center',
    '_input_cache_invalidate',

    # String/number utilities
    '_st_strlen',
    '_fast_u8_to_str',

    # esxDOS
    '_esx_fopen',
    '_esx_fread',
    '_esx_fwrite',
    '_esx_fcreate',
    '_esx_fclose',

    # Config save helpers (ASM frameless callees)
    '_cfg_put',
    '_cfg_kv',

    # Input / frame sync / dither / globe (for globe animation)
    '_in_inkey',
    '_frame_wait',
    '_fill_dither_rows',
    '_render_globe',

    # Screen output (for save status messages)
    '_main_puts',
    '_main_print',
    '_set_attr_sys',
    '_ui_err',
    '_u16_to_dec',

    # SDCC runtime (called implicitly by compiled C)
    '___sdcc_enter_ix',
    '____sdcc_2_copy_src_mhl_dst_deix',
    '____sdcc_4_push_hlix',
]

REQUIRED_VARIABLES = [
    # esxDOS state
    '_esx_handle', '_esx_buf', '_esx_count', '_esx_result',

    # Overlay state
    '_overlay_mode', '_help_page', '_config_dirty', '_notif_enabled',

    # Buffers
    '_overlay_slot', '_ring_buffer',
    '_rb_head', '_rb_tail', '_rx_pos',

    # Theme / print cursor
    '_theme_attrs', '_theme_raw', '_g_ps64_y', '_g_ps64_col',

    # Connection state + channels (for status overlay)
    '_connection_state', '_channels',
    '_network_name', '_ping_latency', '_uptime_minutes',

    # Shared strings
    '_K_DAT', '_S_APPDESC',

    # Config variables (read-only from overlay)
    '_irc_nick', '_irc_server', '_irc_port', '_irc_pass', '_nickserv_pass', '_nickserv_nick',
    '_current_theme', '_beep_enabled', '_keyclick_enabled', '_nick_color_mode', '_show_traffic',
    '_show_timestamps', '_autoconnect', '_autoaway_minutes', '_sntp_tz',
    '_friend_nicks', '_ignore_list', '_ignore_count',
]


def parse_map(map_path):
    """Extract symbol addresses from .map file."""
    symbols = {}
    with open(map_path, 'r', errors='replace') as f:
        for line in f:
            m = re.match(r'(\w+)\s+=\s+\$([0-9A-Fa-f]+)\s+;', line)
            if m:
                symbols[m.group(1)] = int(m.group(2), 16)
    return symbols


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_overlay_defs.py <map_file>", file=sys.stderr)
        sys.exit(1)

    symbols = parse_map(sys.argv[1])

    print(";; AUTO-GENERATED by gen_overlay_defs.py -- DO NOT EDIT")
    print(";; Resident binary symbols for overlay linking (PUBLIC + DEFC)")
    print()

    missing = []
    for name in REQUIRED_FUNCTIONS + REQUIRED_VARIABLES:
        if name in symbols:
            print(f"PUBLIC {name}")
            print(f"DEFC {name} = ${symbols[name]:04X}")
        else:
            missing.append(name)
            print(f";; WARNING: {name} not found in .map!")

    if missing:
        print(f"\n;; MISSING SYMBOLS: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
