#!/usr/bin/env python3
"""
Generate whatsnew_data.h from release/ assets.
Converts logo PNG to monochrome ZX bitmap and packs changelog text.

Usage: python tools/gen_whatsnew.py
Reads:  release/logo.png, release/changes.txt, release/version.txt
Writes: build/whatsnew_data.h

For each new version: update the 3 files in release/, run make.
"""

import sys
from pathlib import Path

def convert_logo(png_path, max_w=80, max_h=88, threshold=40):
    """Convert PNG to monochrome ZX bitmap. Returns (bytes, width_bytes, height)."""
    from PIL import Image
    img = Image.open(png_path).convert('L')

    # Scale preserving aspect ratio, fit within max_w x max_h
    ratio = min(max_w / img.width, max_h / img.height)
    new_w = int(img.width * ratio) & ~7  # align to 8px
    new_h = int(img.height * ratio)
    if new_w == 0: new_w = 8
    img = img.resize((new_w, new_h), Image.LANCZOS)

    pixels = img.load()
    result = bytearray()
    for y in range(new_h):
        for bx in range(new_w // 8):
            byte = 0
            for bit in range(8):
                if pixels[bx * 8 + bit, y] > threshold:
                    byte |= (0x80 >> bit)
            result.append(byte)

    return bytes(result), new_w // 8, new_h


def main():
    base = Path('release')
    out = Path('overlay/whatsnew_data.h')

    # Read version
    version = (base / 'version.txt').read_text().strip()

    # Read changes
    changes = [l.strip() for l in (base / 'changes.txt').read_text().splitlines() if l.strip()]

    # Convert logo
    logo_data, logo_wb, logo_h = convert_logo(base / 'logo.png')

    # Generate C header
    lines = [
        '/* AUTO-GENERATED by gen_whatsnew.py -- DO NOT EDIT */',
        '',
        f'#define WN_VERSION "{version}"',
        f'#define WN_LOGO_WB {logo_wb}   /* bytes per row ({logo_wb*8}px) */',
        f'#define WN_LOGO_H  {logo_h}   /* rows */',
        f'#define WN_CHANGES {len(changes)}',
        '',
        f'static const uint8_t wn_logo[{len(logo_data)}] = {{',
    ]

    # Logo data in rows of 16 bytes
    for i in range(0, len(logo_data), 16):
        chunk = logo_data[i:i+16]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'    {hex_str},')

    lines.append('};')
    lines.append('')

    # Changes as packed null-terminated strings
    lines.append('/* Packed changelog: null-terminated entries, walk with pointer */')
    lines.append('static const char wn_changes[] =')
    for c in changes:
        escaped = c.replace('"', '\\"')
        lines.append(f'    "{escaped}\\0"')
    lines.append(';')

    out.write_text('\n'.join(lines) + '\n')
    print(f'  whatsnew_data.h: logo {logo_wb*8}x{logo_h} ({len(logo_data)}B), '
          f'{len(changes)} changes, version "{version}"')


if __name__ == '__main__':
    main()
